---
 - name: Eliminar paquetes relacionados con Docker y Podman
   yum:
     name: "{{ item }}"
     state: absent
   with_items:
     - docker
     - docker-client
     - docker-client-latest
     - docker-common
     - docker-latest
     - docker-latest-logrotate
     - docker-logrotate
     - docker-engine
     - podman
     - run 
 - name: Instalar yum-utils
   yum:
     name: yum-utils
     state: present